# Alko wine price prediction

In [111]:
import pandas as pd

url = "https://raw.githubusercontent.com/Tyynekaisa/alko-hinnasto/refs/heads/main/data/alko.csv"

alko_data = pd.read_csv(url, sep=";", skiprows=3)

print(alko_data.columns)
display(alko_data.head())

alko_data = alko_data[
    alko_data["Tyyppi"].isin(["valkoviinit", "punaviinit", "roseeviinit"])
]

print(alko_data["Vuosikerta"].unique())

# Filtering bottle size

alko_wines_filtered = alko_data[alko_data["Pullokoko"] == "0.75 l"]

display(alko_wines_filtered.describe())

display(alko_wines_filtered.head(10))

Index(['Numero', 'Nimi', 'Valmistaja', 'Pullokoko', 'Hinta', 'Litrahinta',
       'Uutuus', 'Hinnastojärjestyskoodi', 'Tyyppi', 'Alatyyppi',
       'Erityisryhmä', 'Oluttyyppi', 'Valmistusmaa', 'Alue', 'Vuosikerta',
       'Etikettimerkintöjä', 'Huomautus', 'Rypäleet', 'Luonnehdinta',
       'Pakkaustyyppi', 'Suljentatyyppi', 'Alkoholi-%', 'Hapot g/l',
       'Sokeri g/l', 'Kantavierrep-%', 'Väri EBC', 'Katkerot EBU',
       'Energia kcal/100 ml', 'Valikoima', 'EAN'],
      dtype='object')

,Numero,Nimi,Valmistaja,Pullokoko,Hinta,Litrahinta,Uutuus,Hinnastojärjestyskoodi,Tyyppi,Alatyyppi,...,Suljentatyyppi,Alkoholi-%,Hapot g/l,Sokeri g/l,Kantavierrep-%,Väri EBC,Katkerot EBU,Energia kcal/100 ml,Valikoima,EAN
0,906458,Fair & Square Red 2024 kartonkitölkki,La Riojana,1 l,11.98,11.98,NaN,110,punaviinit,Mehevä & Hilloinen,...,muovisuljin,13.0,5.2,4.0,NaN,NaN,NaN,80.0,vakiovalikoima,7.350085e+12
1,447237,Alambrado Cabernet Sauvignon Malbec 2024,Bodega Santa Julia,0.75 l,12.99,17.19,NaN,110,punaviinit,Pehmeä & Hedelmäinen,...,metallinen kierrekapseli,14.0,5.5,6.0,NaN,NaN,NaN,80.0,vakiovalikoima,7.791728e+12
2,440567,Alamos Malbec Organic 2023,Alamos,0.75 l,12.90,17.07,NaN,110,punaviinit,Mehevä & Hilloinen,...,metallinen kierrekapseli,13.0,5.2,2.0,NaN,NaN,NaN,70.0,vakiovalikoima,7.794450e+12
3,939055,Altos Las Hormigas Clásico Malbec 2021,Altos Las Hormigas,0.75 l,22.99,30.65,NaN,110,punaviinit,Mehevä & Hilloinen,...,luonnonkorkki,13.5,5.5,3.0,NaN,NaN,NaN,80.0,tilausvalikoima,7.798052e+12
4,903027,Beefsteak Club Reserve Barrel Aged Malbec 2020,Andean Vineyards,0.75 l,29.97,39.96,NaN,110,punaviinit,Vivahteikas & Kehittynyt,...,luonnonkorkki,14.5,5.1,3.0,NaN,NaN,NaN,80.0,tilausvalikoima,5.011932e+12

[2024. 2023. 2021. 2020. 2022.   nan 2019. 2015. 2018. 2025. 2017. 2014.
 2007. 2016. 2003. 2009. 2012. 2013. 2010. 2001. 2011. 1985. 1994. 1981.
 2000. 2005. 2002. 2006. 1983. 1926. 2008.]

,Numero,Hinta,Litrahinta,Vuosikerta,Alkoholi-%,Hapot g/l,Sokeri g/l,Kantavierrep-%,Väri EBC,Katkerot EBU,Energia kcal/100 ml,EAN
count,5168.000000,5168.000000,5168.000000,4972.000000,5168.000000,5155.000000,5168.000000,0.0,0.0,0.0,5168.000000,5.148000e+03
mean,760642.465170,52.095391,69.399632,2021.015084,13.246267,5.651232,3.510062,NaN,NaN,NaN,75.700464,6.128930e+12
std,238225.397291,159.009951,212.025670,3.173577,1.165699,0.842461,7.274718,NaN,NaN,NaN,5.958769,2.696298e+12
min,4246.000000,6.990000,9.190000,1926.000000,5.000000,3.500000,0.000000,NaN,NaN,NaN,50.000000,0.000000e+00
25%,511187.000000,15.497500,20.640000,2020.000000,12.500000,5.100000,0.000000,NaN,NaN,NaN,70.000000,3.760193e+12
50%,902120.000000,22.980000,30.530000,2022.000000,13.500000,5.500000,1.000000,NaN,NaN,NaN,80.000000,6.430070e+12
75%,929487.750000,40.037500,53.385000,2023.000000,14.000000,6.000000,4.000000,NaN,NaN,NaN,80.000000,8.052433e+12
max,959994.000000,5990.000000,7986.670000,2025.000000,18.000000,10.500000,139.000000,NaN,NaN,NaN,110.000000,8.059482e+13

,Numero,Nimi,Valmistaja,Pullokoko,Hinta,Litrahinta,Uutuus,Hinnastojärjestyskoodi,Tyyppi,Alatyyppi,...,Suljentatyyppi,Alkoholi-%,Hapot g/l,Sokeri g/l,Kantavierrep-%,Väri EBC,Katkerot EBU,Energia kcal/100 ml,Valikoima,EAN
1,447237,Alambrado Cabernet Sauvignon Malbec 2024,Bodega Santa Julia,0.75 l,12.99,17.19,NaN,110,punaviinit,Pehmeä & Hedelmäinen,...,metallinen kierrekapseli,14.0,5.5,6.0,NaN,NaN,NaN,80.0,vakiovalikoima,7.791728e+12
2,440567,Alamos Malbec Organic 2023,Alamos,0.75 l,12.90,17.07,NaN,110,punaviinit,Mehevä & Hilloinen,...,metallinen kierrekapseli,13.0,5.2,2.0,NaN,NaN,NaN,70.0,vakiovalikoima,7.794450e+12
3,939055,Altos Las Hormigas Clásico Malbec 2021,Altos Las Hormigas,0.75 l,22.99,30.65,NaN,110,punaviinit,Mehevä & Hilloinen,...,luonnonkorkki,13.5,5.5,3.0,NaN,NaN,NaN,80.0,tilausvalikoima,7.798052e+12
4,903027,Beefsteak Club Reserve Barrel Aged Malbec 2020,Andean Vineyards,0.75 l,29.97,39.96,NaN,110,punaviinit,Vivahteikas & Kehittynyt,...,luonnonkorkki,14.5,5.1,3.0,NaN,NaN,NaN,80.0,tilausvalikoima,5.011932e+12
5,924067,Beefsteak Club Reserve Malbec 2024,E. I. Wines,0.75 l,15.50,20.53,NaN,110,punaviinit,Mehevä & Hilloinen,...,metallinen kierrekapseli,13.0,5.2,3.0,NaN,NaN,NaN,70.0,tilausvalikoima,5.011932e+12
7,446837,BenMarco Malbec 2022,Dominio del Plata,0.75 l,24.90,33.07,NaN,110,punaviinit,Mehevä & Hilloinen,...,luonnonkorkki,14.5,5.6,0.0,NaN,NaN,NaN,80.0,vakiovalikoima,7.798068e+12
8,400026,Bianchi Gran Famiglia Malbec 2022,Bodegas Bianchi,0.75 l,19.97,26.49,NaN,110,punaviinit,Roteva & Voimakas,...,luonnonkorkki,14.5,5.6,3.0,NaN,NaN,NaN,80.0,erikoiserä,7.790703e+12
9,4551,Caballo de Mendoza,Anora Group,0.75 l,9.61,12.68,NaN,110,punaviinit,Mehevä & Hilloinen,...,metallinen kierrekapseli,14.0,5.3,0.0,NaN,NaN,NaN,80.0,vakiovalikoima,6.412700e+12
10,487307,Cameleon Organic Cabernet Sauvignon 2022,Domaine Bousquet,0.75 l,13.98,18.51,NaN,110,punaviinit,Mehevä & Hilloinen,...,metallinen kierrekapseli,14.0,5.1,0.0,NaN,NaN,NaN,80.0,vakiovalikoima,7.798102e+12
11,411547,Carrascal Cabernet Sauvignon Malbec Organic 2021,Bodega Y Cavas de Weinert,0.75 l,10.98,14.51,NaN,110,punaviinit,Roteva & Voimakas,...,metallinen kierrekapseli,14.0,5.2,4.0,NaN,NaN,NaN,80.0,vakiovalikoima,7.790418e+12

In [112]:
# from data_profiling import ProfileReport

# profile = ProfileReport(
#     alko_wines_filtered, title="Alko Wines Data Profiling Report", explorative=True
# )
# profile.to_file("alko_wines_data_profiling_report.html")

## Removing columns: 'Numero', 'Kantavierrep-%', 'Väri EBC', 'Katkerot EBU', 'Oluttyyppi', 'Uutuus', 'Litrahinta', 'Pullokoko', 'EAN', 'Huomautus', 'Hinnastojärjestyskoodi'

In [113]:
columns_to_remove = [
    "Numero",
    "Kantavierrep-%",
    "Väri EBC",
    "Katkerot EBU",
    "Oluttyyppi",
    "Uutuus",
    "Litrahinta",
    "Pullokoko",
    "EAN",
    "Huomautus",
    "Hinnastojärjestyskoodi",
    "Etikettimerkintöjä",
    "Valmistaja",
    "Alatyyppi",
    "Energia kcal/100 ml",
    "Valikoima",
]

alko_filtered = alko_wines_filtered.drop(columns=columns_to_remove)

display(alko_filtered.head())
print(alko_filtered["Alue"].unique())

,Nimi,Hinta,Tyyppi,Erityisryhmä,Valmistusmaa,Alue,Vuosikerta,Rypäleet,Luonnehdinta,Pakkaustyyppi,Suljentatyyppi,Alkoholi-%,Hapot g/l,Sokeri g/l
1,Alambrado Cabernet Sauvignon Malbec 2024,12.99,punaviinit,Vegaaneille soveltuva tuote,Argentiina,Mendoza,2024.0,"Cabernet Sauvignon, Malbec,","Tummanpunainen, keskitäyteläinen, keskitanniin...",lasipullo,metallinen kierrekapseli,14.0,5.5,6.0
2,Alamos Malbec Organic 2023,12.90,punaviinit,NaN,Argentiina,Mendoza,2023.0,"Malbec,","Tummanpunainen, keskitäyteläinen, keskitanniin...",lasipullo,metallinen kierrekapseli,13.0,5.2,2.0
3,Altos Las Hormigas Clásico Malbec 2021,22.99,punaviinit,NaN,Argentiina,Mendoza,2021.0,"Malbec,","Tummanpunainen, täyteläinen, keskitanniininen,...",lasipullo,luonnonkorkki,13.5,5.5,3.0
4,Beefsteak Club Reserve Barrel Aged Malbec 2020,29.97,punaviinit,NaN,Argentiina,Mendoza,2020.0,"Malbec,","Rubiininpunainen, täyteläinen, keskitanniinine...",lasipullo,luonnonkorkki,14.5,5.1,3.0
5,Beefsteak Club Reserve Malbec 2024,15.50,punaviinit,Vegaaneille soveltuva tuote,Argentiina,Mendoza,2024.0,"Malbec,","Runsaanpunainen, keskitäyteläinen, keskitannii...",lasipullo,metallinen kierrekapseli,13.0,5.2,3.0

['Mendoza' 'Patagonia' 'Salta' 'San Juan' nan 'Muut' 'New South Wales'
 'South Australia' 'Tasmania' 'Victoria' 'Western Australia' 'Aconcagua'
 'Valle Central' 'Valle del Bío Bío' 'Valle del Elqui' 'Valle del Itata'
 'Valle del Limarí' 'Aragonia' 'Galicia' 'Kastilia-La Mancha'
 'Kastilia-León' 'Katalonia' 'Levante' 'Navarra' 'Rioja'
 'Breede River Valley' 'Cape South Coast' 'Coastal Region' 'Abruzzit'
 'Apulia' 'Basilicata' 'Emilia-Romagna' 'Friuli' 'Kalabria' 'Kampania'
 'Lazio' 'Lombardia' 'Marche' 'Piemonte' 'Sardinia' 'Sisilia' 'Toscana'
 'Trentino-Alto Adige' 'Umbria' 'Veneto' 'Burgenland' 'Niederösterreich'
 'Ontario' 'Alentejo' 'Douro' 'Lisboa' 'Tejo' 'Vinho Verde' 'Alsace'
 'Bordeaux' 'Bourgogne' 'Jura' 'Languedoc-Roussillon' 'Loire'
 'Lounais-Ranska' 'Provence' 'Rhône' 'Savoie' 'Baden' 'Franken' 'Mosel'
 'Pfalz' 'Rheingau' 'Rheinhessen' 'Württemberg' 'Canterbury'
 'Central Otago' "Hawke's Bay" 'Marlborough' 'Martinborough' 'Nelson'
 'Kalifornia' 'Oregon' 'Washington' 'Nahe' 'Waipara' 'Buenos Aires'
 'La Rioja' 'Steiermark' 'British Columbia' 'Hessische Bergstrasse'
 'Sachsen']

## Deal with missing values

In [114]:
# Missing means category does not apply
alko_filtered["Erityisryhmä"] = alko_filtered["Erityisryhmä"].fillna("None")

# Genuinely unknown / unspecified
alko_filtered["Alue"] = alko_filtered["Alue"].fillna("Unknown")
alko_filtered["Rypäleet"] = alko_filtered["Rypäleet"].fillna("Unknown")

# Missing vintage is meaningful
alko_filtered["HasVuosikerta"] = alko_filtered["Vuosikerta"].notna().astype(int)

# Missing text
alko_filtered["Luonnehdinta"] = alko_filtered["Luonnehdinta"].fillna("")

## Split grapes from string into a list of strings

In [115]:
def parse_multilabel(value):
    if pd.isna(value):
        return ["unknown"]

    return [item.strip().lower() for item in value.split(",") if item.strip()]


alko_filtered["Rypäleet"] = alko_filtered["Rypäleet"].apply(parse_multilabel)
alko_filtered["Luonnehdinta"] = alko_filtered["Luonnehdinta"].apply(parse_multilabel)

print(alko_filtered["Rypäleet"].head())
print(alko_filtered["Luonnehdinta"].head())

# Check whether Luonnehdinta has a reusable multi-label vocabulary.
descriptions = alko_filtered["Luonnehdinta"]
description_counts = pd.Series(
    [label for labels in descriptions for label in set(labels)]
).value_counts()
labels_per_wine = descriptions.apply(len)
wine_count = len(descriptions)

print(f"\nWines with no descriptors: {(labels_per_wine == 0).sum()} / {wine_count}")
print(f"Unique descriptor labels: {len(description_counts)}")
print("Descriptors per wine:")
print(labels_per_wine.describe())
print(
    "Labels appearing in 1 / <=5 / <=10 wines:",
    (description_counts == 1).sum(),
    (description_counts <= 5).sum(),
    (description_counts <= 10).sum(),
)
print("Most common descriptors (counted by wines):")
print(description_counts.head(30).to_frame("wine_count"))

1    [cabernet sauvignon, malbec]
2                        [malbec]
3                        [malbec]
4                        [malbec]
5                        [malbec]
Name: Rypäleet, dtype: object
1    [tummanpunainen, keskitäyteläinen, keskitannii...
2    [tummanpunainen, keskitäyteläinen, keskitannii...
3    [tummanpunainen, täyteläinen, keskitanniininen...
4    [rubiininpunainen, täyteläinen, keskitanniinin...
5    [runsaanpunainen, keskitäyteläinen, keskitanni...
Name: Luonnehdinta, dtype: object

Wines with no descriptors: 0 / 5168
Unique descriptor labels: 694
Descriptors per wine:
count    5168.000000
mean        6.937887
std         1.376421
min         4.000000
25%         6.000000
50%         6.000000
75%         8.000000
max        14.000000
Name: Luonnehdinta, dtype: float64
Labels appearing in 1 / <=5 / <=10 wines: 177 369 461
Most common descriptors (counted by wines):
                     wine_count
kuiva                      1956
täyteläinen                1626
hapokas                    1579
tanniininen                1382
keskitanniininen           1358
mausteinen                 1265
keskitäyteläinen           1049
tummanpunainen              935
sitruksinen                 882
tumman kirsikkainen         780
kirsikkainen                736
karhunvatukkainen           732
tamminen                    716
vaaleankeltainen            640
yrttinen                    640
mineraalinen                611
keskihapokas                493
luumuinen                   476
mustaherukkainen            460
runsaanpunainen             455
rubiininpunainen            453
viheromenainen              391
punainen                    390
vadelmainen                 364
hapankirsikkainen           356
herukkainen                 343
kukkainen                   331
karpaloinen                 310
persikkainen                305
aprikoosinen                299

## Encode features

Fit encoders on the training split only. `OneHotEncoder.min_frequency` groups rare single categories; `MultiLabelBinarizer` has no minimum-frequency parameter, so rare labels are grouped into an infrequent label using training-set counts.

In [116]:
from collections import Counter

import numpy as np
from scipy.sparse import csr_matrix, hstack
from sklearn.impute import SimpleImputer
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MultiLabelBinarizer, OneHotEncoder

CATEGORICAL_FEATURES = [
    "Tyyppi",
    "Erityisryhmä",
    "Valmistusmaa",
    "Alue",
    "Pakkaustyyppi",
    "Suljentatyyppi",
]

MULTILABEL_FEATURES = ["Rypäleet", "Luonnehdinta"]

NUMERIC_FEATURES = [
    "Vuosikerta",
    "Alkoholi-%",
    "Hapot g/l",
    "Sokeri g/l",
    "HasVuosikerta",
]

TARGET = "Hinta"

MIN_CATEGORY_FREQUENCY = 100
MIN_LABEL_FREQUENCY = 100
INFREQUENT_LABEL = "__infrequent__"


# Clean normal categorical features BEFORE creating X and train/test split.
for column in CATEGORICAL_FEATURES:
    alko_filtered[column] = (
        alko_filtered[column].fillna("unknown").astype(str).str.strip().str.lower()
    )


feature_columns = CATEGORICAL_FEATURES + MULTILABEL_FEATURES + NUMERIC_FEATURES

X = alko_filtered[feature_columns].copy()
y = alko_filtered[TARGET].copy()

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
)


# One value per wine.
one_hot_encoder = OneHotEncoder(
    handle_unknown="infrequent_if_exist",
    min_frequency=MIN_CATEGORY_FREQUENCY,
    sparse_output=True,
)

X_train_one_hot = one_hot_encoder.fit_transform(X_train[CATEGORICAL_FEATURES])

X_test_one_hot = one_hot_encoder.transform(X_test[CATEGORICAL_FEATURES])


# Multiple labels per wine.
multilabel_encoders = {}
X_train_multilabel = []
X_test_multilabel = []
multilabel_feature_names = []

for column in MULTILABEL_FEATURES:
    train_labels = X_train[column]

    label_counts = Counter(label for labels in train_labels for label in set(labels))

    frequent_labels = {
        label for label, count in label_counts.items() if count >= MIN_LABEL_FREQUENCY
    }

    has_infrequent_labels = len(frequent_labels) < len(label_counts)

    def group_rare_labels(label_lists):
        grouped = []

        for labels in label_lists:
            kept = {label for label in labels if label in frequent_labels}

            if has_infrequent_labels and any(
                label not in frequent_labels for label in labels
            ):
                kept.add(INFREQUENT_LABEL)

            grouped.append(sorted(kept))

        return grouped

    encoder = MultiLabelBinarizer(sparse_output=True)

    train_values = group_rare_labels(train_labels)
    test_values = group_rare_labels(X_test[column])

    X_train_multilabel.append(encoder.fit_transform(train_values))

    X_test_multilabel.append(encoder.transform(test_values))

    multilabel_encoders[column] = encoder

    multilabel_feature_names.extend(f"{column}__{label}" for label in encoder.classes_)

    print(
        f"{column}: {len(label_counts)} labels in train, "
        f"{len(frequent_labels)} retained individually, "
        f"{int(has_infrequent_labels)} infrequent bucket"
    )


# Impute missing numeric values using training-set medians.
numeric_imputer = SimpleImputer(strategy="median")

X_train_numeric = csr_matrix(numeric_imputer.fit_transform(X_train[NUMERIC_FEATURES]))

X_test_numeric = csr_matrix(numeric_imputer.transform(X_test[NUMERIC_FEATURES]))


# Combine everything.
X_train_encoded = hstack(
    [
        X_train_one_hot,
        *X_train_multilabel,
        X_train_numeric,
    ],
    format="csr",
)

X_test_encoded = hstack(
    [
        X_test_one_hot,
        *X_test_multilabel,
        X_test_numeric,
    ],
    format="csr",
)


encoded_feature_names = np.concatenate(
    [
        one_hot_encoder.get_feature_names_out(CATEGORICAL_FEATURES),
        multilabel_feature_names,
        NUMERIC_FEATURES,
    ]
)


print("Encoded train shape:", X_train_encoded.shape)
print("Encoded test shape:", X_test_encoded.shape)
print(
    "Feature names match encoded columns:",
    len(encoded_feature_names) == X_train_encoded.shape[1],
)

Rypäleet: 403 labels in train, 16 retained individually, 1 infrequent bucket
Luonnehdinta: 653 labels in train, 58 retained individually, 1 infrequent bucket
Encoded train shape: (4134, 117)
Encoded test shape: (1034, 117)
Feature names match encoded columns: True