# Alko wine price prediction

In [13]:
import pandas as pd

url = "https://raw.githubusercontent.com/Tyynekaisa/alko-hinnasto/refs/heads/main/data/alko.csv"

alko_data = pd.read_csv(url, sep=";", skiprows=3)

print(alko_data.columns)
display(alko_data.head())

alko_data = alko_data[
    alko_data["Tyyppi"].isin(["valkoviinit", "punaviinit", "roseeviinit"])
]

print(alko_data["Vuosikerta"].unique())

# Filtering bottle size

alko_wines_filtered = alko_data[alko_data["Pullokoko"] == "0.75 l"]

display(alko_wines_filtered.describe())

display(alko_wines_filtered.head(10))

Index(['Numero', 'Nimi', 'Valmistaja', 'Pullokoko', 'Hinta', 'Litrahinta',
       'Uutuus', 'Hinnastojärjestyskoodi', 'Tyyppi', 'Alatyyppi',
       'Erityisryhmä', 'Oluttyyppi', 'Valmistusmaa', 'Alue', 'Vuosikerta',
       'Etikettimerkintöjä', 'Huomautus', 'Rypäleet', 'Luonnehdinta',
       'Pakkaustyyppi', 'Suljentatyyppi', 'Alkoholi-%', 'Hapot g/l',
       'Sokeri g/l', 'Kantavierrep-%', 'Väri EBC', 'Katkerot EBU',
       'Energia kcal/100 ml', 'Valikoima', 'EAN'],
      dtype='str')

,Numero,Nimi,Valmistaja,Pullokoko,Hinta,Litrahinta,Uutuus,Hinnastojärjestyskoodi,Tyyppi,Alatyyppi,...,Suljentatyyppi,Alkoholi-%,Hapot g/l,Sokeri g/l,Kantavierrep-%,Väri EBC,Katkerot EBU,Energia kcal/100 ml,Valikoima,EAN
0,906458,Fair & Square Red 2024 kartonkitölkki,La Riojana,1 l,11.98,11.98,NaN,110,punaviinit,Mehevä & Hilloinen,...,muovisuljin,13.0,5.2,4.0,NaN,NaN,NaN,80.0,vakiovalikoima,7.350085e+12
1,447237,Alambrado Cabernet Sauvignon Malbec 2024,Bodega Santa Julia,0.75 l,12.99,17.19,NaN,110,punaviinit,Pehmeä & Hedelmäinen,...,metallinen kierrekapseli,14.0,5.5,6.0,NaN,NaN,NaN,80.0,vakiovalikoima,7.791728e+12
2,440567,Alamos Malbec Organic 2023,Alamos,0.75 l,12.90,17.07,NaN,110,punaviinit,Mehevä & Hilloinen,...,metallinen kierrekapseli,13.0,5.2,2.0,NaN,NaN,NaN,70.0,vakiovalikoima,7.794450e+12
3,939055,Altos Las Hormigas Clásico Malbec 2021,Altos Las Hormigas,0.75 l,22.99,30.65,NaN,110,punaviinit,Mehevä & Hilloinen,...,luonnonkorkki,13.5,5.5,3.0,NaN,NaN,NaN,80.0,tilausvalikoima,7.798052e+12
4,903027,Beefsteak Club Reserve Barrel Aged Malbec 2020,Andean Vineyards,0.75 l,29.97,39.96,NaN,110,punaviinit,Vivahteikas & Kehittynyt,...,luonnonkorkki,14.5,5.1,3.0,NaN,NaN,NaN,80.0,tilausvalikoima,5.011932e+12

[2024. 2023. 2021. 2020. 2022.   nan 2019. 2015. 2018. 2025. 2017. 2014.
 2007. 2016. 2003. 2009. 2012. 2013. 2010. 2001. 2011. 1985. 1994. 1981.
 2000. 2005. 2002. 2006. 1983. 1926. 2008.]

,Numero,Hinta,Litrahinta,Vuosikerta,Alkoholi-%,Hapot g/l,Sokeri g/l,Kantavierrep-%,Väri EBC,Katkerot EBU,Energia kcal/100 ml,EAN
count,5168.000000,5168.000000,5168.000000,4972.000000,5168.000000,5155.000000,5168.000000,0.0,0.0,0.0,5168.000000,5.148000e+03
mean,760642.465170,52.095391,69.399632,2021.015084,13.246267,5.651232,3.510062,NaN,NaN,NaN,75.700464,6.128930e+12
std,238225.397291,159.009951,212.025670,3.173577,1.165699,0.842461,7.274718,NaN,NaN,NaN,5.958769,2.696298e+12
min,4246.000000,6.990000,9.190000,1926.000000,5.000000,3.500000,0.000000,NaN,NaN,NaN,50.000000,0.000000e+00
25%,511187.000000,15.497500,20.640000,2020.000000,12.500000,5.100000,0.000000,NaN,NaN,NaN,70.000000,3.760193e+12
50%,902120.000000,22.980000,30.530000,2022.000000,13.500000,5.500000,1.000000,NaN,NaN,NaN,80.000000,6.430070e+12
75%,929487.750000,40.037500,53.385000,2023.000000,14.000000,6.000000,4.000000,NaN,NaN,NaN,80.000000,8.052433e+12
max,959994.000000,5990.000000,7986.670000,2025.000000,18.000000,10.500000,139.000000,NaN,NaN,NaN,110.000000,8.059482e+13

,Numero,Nimi,Valmistaja,Pullokoko,Hinta,Litrahinta,Uutuus,Hinnastojärjestyskoodi,Tyyppi,Alatyyppi,...,Suljentatyyppi,Alkoholi-%,Hapot g/l,Sokeri g/l,Kantavierrep-%,Väri EBC,Katkerot EBU,Energia kcal/100 ml,Valikoima,EAN
1,447237,Alambrado Cabernet Sauvignon Malbec 2024,Bodega Santa Julia,0.75 l,12.99,17.19,NaN,110,punaviinit,Pehmeä & Hedelmäinen,...,metallinen kierrekapseli,14.0,5.5,6.0,NaN,NaN,NaN,80.0,vakiovalikoima,7.791728e+12
2,440567,Alamos Malbec Organic 2023,Alamos,0.75 l,12.90,17.07,NaN,110,punaviinit,Mehevä & Hilloinen,...,metallinen kierrekapseli,13.0,5.2,2.0,NaN,NaN,NaN,70.0,vakiovalikoima,7.794450e+12
3,939055,Altos Las Hormigas Clásico Malbec 2021,Altos Las Hormigas,0.75 l,22.99,30.65,NaN,110,punaviinit,Mehevä & Hilloinen,...,luonnonkorkki,13.5,5.5,3.0,NaN,NaN,NaN,80.0,tilausvalikoima,7.798052e+12
4,903027,Beefsteak Club Reserve Barrel Aged Malbec 2020,Andean Vineyards,0.75 l,29.97,39.96,NaN,110,punaviinit,Vivahteikas & Kehittynyt,...,luonnonkorkki,14.5,5.1,3.0,NaN,NaN,NaN,80.0,tilausvalikoima,5.011932e+12
5,924067,Beefsteak Club Reserve Malbec 2024,E. I. Wines,0.75 l,15.50,20.53,NaN,110,punaviinit,Mehevä & Hilloinen,...,metallinen kierrekapseli,13.0,5.2,3.0,NaN,NaN,NaN,70.0,tilausvalikoima,5.011932e+12
7,446837,BenMarco Malbec 2022,Dominio del Plata,0.75 l,24.90,33.07,NaN,110,punaviinit,Mehevä & Hilloinen,...,luonnonkorkki,14.5,5.6,0.0,NaN,NaN,NaN,80.0,vakiovalikoima,7.798068e+12
8,400026,Bianchi Gran Famiglia Malbec 2022,Bodegas Bianchi,0.75 l,19.97,26.49,NaN,110,punaviinit,Roteva & Voimakas,...,luonnonkorkki,14.5,5.6,3.0,NaN,NaN,NaN,80.0,erikoiserä,7.790703e+12
9,4551,Caballo de Mendoza,Anora Group,0.75 l,9.61,12.68,NaN,110,punaviinit,Mehevä & Hilloinen,...,metallinen kierrekapseli,14.0,5.3,0.0,NaN,NaN,NaN,80.0,vakiovalikoima,6.412700e+12
10,487307,Cameleon Organic Cabernet Sauvignon 2022,Domaine Bousquet,0.75 l,13.98,18.51,NaN,110,punaviinit,Mehevä & Hilloinen,...,metallinen kierrekapseli,14.0,5.1,0.0,NaN,NaN,NaN,80.0,vakiovalikoima,7.798102e+12
11,411547,Carrascal Cabernet Sauvignon Malbec Organic 2021,Bodega Y Cavas de Weinert,0.75 l,10.98,14.51,NaN,110,punaviinit,Roteva & Voimakas,...,metallinen kierrekapseli,14.0,5.2,4.0,NaN,NaN,NaN,80.0,vakiovalikoima,7.790418e+12

In [ ]:
from data_profiling import ProfileReport

profile = ProfileReport(
    alko_wines_filtered, title="Alko Wines Data Profiling Report", explorative=True
)
profile.to_file("alko_wines_data_profiling_report.html")

100%|██████████| 30/30 [00:00<00:00, 958.06it/s]<00:00, 100.65it/s, Describe variable: EAN]
Summarize dataset: 100%|██████████| 121/121 [00:03<00:00, 39.56it/s, Completed]
Generate report structure: 100%|██████████| 1/1 [00:02<00:00,  2.02s/it]
Render HTML: 100%|██████████| 1/1 [00:00<00:00,  2.58it/s]
Export report to file: 100%|██████████| 1/1 [00:00<00:00, 307.86it/s]